### ISSUE TITLE
Logo fix

### ISSUE THREAD

**Issue by Yekez** [acikkaynak/tercuman-bul-app#14]
Header logo can be seen on local. Prod does not have it.
![image](https://user-images.githubusercontent.com/64737937/218282347-752b6b68-1062-4bd4-a6cf-7625ed30a105.png)
![image](https://user-images.githubusercontent.com/64737937/218282363-7d9a11a1-b4a2-4766-975d-d03adc960c37.png)

**Comment by Yekez** [comment]
We should assign someone who has access to backend. I tried what I could, probably not client related.

**Comment by xsorifc28** [comment]
Fixed
