### ISSUE TITLE
Bug: Sign in/up with google

### ISSUE THREAD

**Issue by Yekez** [acikkaynak/tercuman-bul-app#21]
Button does not work.

Commit hash as of now: [f85e05b](https://github.com/acikkaynak/tercuman-bul-app/commit/f85e05b41ce5b8d7f3981400657df70bf969995c)
Browser: Brave

**Comment by xsorifc28** [comment]
It was broken before this commit - it broke when we started using custom sign in UI instead of FirebaseAuthUI.

Didn't get a change to look at this, but I think @yunusemrecetin can help out here.

**Comment by Yekez** [comment]
We should assign him. I think I don't have assign perms

**Comment by xsorifc28** [comment]
Moved to trello
