### ISSUE TITLE
Brand name and logo

### ISSUE THREAD

**Issue by yamac-kurtulus** [acikkaynak/tercuman-bul-app#6]
by @designhunt360

**Comment by xsorifc28** [comment]
Bunu simdilik tamam diyorum, uiux takiminin verdigi logolarla devam ediyoruz:
https://www.figma.com/file/d8ZDzUJ6Z66XniJ94WAtDV/Terc%C3%BCman%C4%B1m%C4%B1-Bul?node-id=270%3A43611&t=ZbGzO1lCHjGaT0rl-0
